version: '3.8'
services:
    gateway:
        build: ./services/api-gateway-service
        restart: always
        hostname: gateway
        ports:
            - "3000:3000"
        container_name: elias-gateway
        networks:
            - elias
    company:
        build: ./services/company-service
        restart: always
        hostname: company
        ports:
            - "3002:3002"
        container_name: elias-companies
        networks:
            - elias
networks:
    elias:
        driver: bridge
