version: '3.8'
services:
    rider-securitydb:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        container_name: rider-security-mongo
        networks:
            - rider-security
    gateway:
        build: ./services/api-gateway-service
        restart: always
        hostname: gateway
        ports:
            - "3000:3000"
        depends_on:
            - rider-securitydb
        container_name: rider-security-gateway
        networks:
            - rider-security
        environment:
            - MONGO_URL=mongodb+srv://EliasMerlo:knhHtq4P6yA38t5P@cluster0.mjgvmh2.mongodb.net/RiderSecurity
            - GATEWAY_PORT=3000
            - USER_HOST=user
            - USER_SERVICE_PORT=3001
            - COMPANY_HOST=company
            - COMPANY_SERVICE_PORT=3002
    user:
        build: ./services/user-service
        restart: always
        hostname: user
        ports:
            - "3001:3001"
        depends_on:
            - rider-securitydb
        container_name: rider-security-users
        networks:
            - rider-security
        environment:
            - MONGO_URL=mongodb+srv://EliasMerlo:knhHtq4P6yA38t5P@cluster0.mjgvmh2.mongodb.net/RiderSecurity
            - USER_HOST=user 
            - USER_SERVICE_PORT=3001
    company:
        build: ./services/company-service
        restart: always
        hostname: company
        ports:
            - "3002:3002"
        depends_on:
            - rider-securitydb
        container_name: rider-security-companies
        networks:
            - rider-security
        environment:
            - MONGO_URL=mongodb+srv://EliasMerlo:knhHtq4P6yA38t5P@cluster0.mjgvmh2.mongodb.net/RiderSecurity
            - COMPANY_HOST=company 
            - COMPANY_SERVICE_PORT=3002
networks:
    rider-security:
        driver: bridge
